name: skema_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.11
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - matplotlib=3.7.5
  - tifffile=2023.4.12
  - rasterio=1.4.3
  - tqdm=4.67.1
  - click=8.2.0
  - pip:
      - torch==2.7.0
      - torchvision==0.22.0
      - pytorch-lightning==2.5.1.post0
      - segmentation-models-pytorch==0.5.0
      - torchmetrics==1.7.1
      - albumentations==1.4.24
      - skema @ file:///C:/skema/dist/skema-0.1.0-py3-none-any.whl  # if installing from local wheel
