name: skema_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.8,<3.13
  - pip
  - numpy=1.26.4
  - scikit-learn=1.3.2
  - rasterio=1.3.11
  - click=8.1.7
  - albumentations=1.4.24
  - torch=2.4.1
  - torchvision=0.19.1
  - rich=13.9.4
  - pip:
      - pytorch-lightning==2.5.1.post0
      - segmentation-models-pytorch==0.5.0
      - torchmetrics==1.7.1